- id: doi:10.1186/s13073-025-01513-w
  image: https://genomemedicine.biomedcentral.com/static/images/bmc/logos/genome-medicine-logo-24b9193f4f.svg

- id: doi:10.1172/jci.insight.176985
  image: https://insight.jci.org/assets/common/insight-white-on-transparent.20160208-0ce7c11085a7b0f6aa8029aca307bb56c445f25824aee58a72026601bab3efca.png

- id: doi:10.1038/s41525-024-00449-1
  image: https://media.springernature.com/full/nature-cms/uploads/product/npjgenmed/header-d59e23e52ffacae5c9f83e58d6f5e610.svg

- id: doi:10.1016/j.ajhg.2024.06.015
  image: https://ars.els-cdn.com/content/image/B00029297.svg

- id: doi:10.1038/s12276-024-01172-8
  image: https://media.springernature.com/full/nature-cms/uploads/product/emm/header-d8217f38d70a68088a50cb0998a1912d.svg

- id: doi:10.1038/s41431-024-01542-w
  image: https://media.springernature.com/full/nature-cms/uploads/product/ejhg/header-d8ba0ed98c6cf5de4fa2ee89c28067ff.svg

- id: doi:10.1002/mds.29275
  image: https://movementdisorders.onlinelibrary.wiley.com/pb-assets/hub-assets/movementdisorders/logo-header-1671178710230.png

- id: doi:10.1002/hep.31862
  image: https://www.aasld.org/themes/custom/aasld_theme/logo.svg
